# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/58a4ee33-3382-4c6d-879e-e18600d10bf3";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-d66b48f8-d100-4bde-9811-d73c96654559".device =
    "/dev/disk/by-uuid/d66b48f8-d100-4bde-9811-d73c96654559";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/BD8D-ADEF";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/3266676d-6c0b-4452-834a-23715d91826e"; }];

  fileSystems."/mnt/adisk" = {
    device = "/dev/disk/by-uuid/f3e39a03-e333-407c-9a02-8c789a6e0a5a";
    fsType = "ext4";
  };

  fileSystems."/mnt/bdisk" = {
    device = "/dev/disk/by-uuid/d99a4472-29a8-446a-acd8-7ffe7be7d405";
    fsType = "ext4";
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp42s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.virbr1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
